export default {
    codexMcp: {
        title: 'Codex MCP Management',
        wslSection: 'WSL: {{distro}}',
        notFound: '~/.codex/config.toml was not found in this environment',
        configPath: 'Config',
        disabledConfigPath: 'Disabled',
        enabledServers: 'Enabled MCP servers',
        disabledServers: 'Disabled MCP servers',
        noServers: 'No MCP servers registered',
        serverName: 'Server name',
        command: 'Command',
        args: 'Args',
        actions: 'Actions',
        enable: 'Enable',
        disable: 'Disable',
        dragToReorder: 'Drag to reorder',
    },
    cleanup: {
        title: 'Codex Cleanup',
        description:
            'Delete history, cache, temporary files, logs, and sessions under ~/.codex. Frees disk space, improves responsiveness, and clears stale state. Config files, credentials, agents, skills, and state DBs (sqlite) are excluded.',
        wslSection: 'WSL: {{distro}}',
        deleteSelected: 'Delete selected',
        cancel: 'Cancel',
        confirmTitle: 'Confirm cleanup',
        confirmBody: 'Delete the {{count}} selected item(s). This cannot be undone. Continue?',
        reclaimable: '{{count}} selected, reclaimable {{size}}',
        noCandidates: 'No cleanup targets found',
        inUseWarning:
            'If a Codex session is running, some directories may fail to delete. Please close sessions before deleting.',
        deleteSuccess: 'Cleanup completed',
        deletePartial: 'Some files were in use and were skipped',
        deleteError: 'Failed to delete some items',
        columnName: 'Item',
        columnDescription: 'Description',
        columnFiles: 'Files',
        columnSize: 'Size',
        dir: {
            sessions: 'sessions',
            cache: 'cache',
            generatedImages: 'generated_images',
            tmp: 'tmp',
            log: 'log',
            modelsCache: 'models_cache.json',
            sessionIndex: 'session_index.jsonl',
        },
        desc: {
            sessions: 'Recorded past sessions (conversation logs / rollouts). Expand by year to delete individually.',
            cache: 'Temporary cache for downloads and various data.',
            generatedImages: 'Storage for images generated by Codex.',
            tmp: 'Temporary working files.',
            log: 'Log output directory.',
            modelsCache: 'Cache of available model information.',
            sessionIndex: 'Index of the session list.',
        },
        other: {
            sectionTitle: 'Other tools',
            registered: '{{count}} registered',
            columnMetric: 'Status',
            label: {
                serenaProjects: 'Serena registered projects',
                serenaLogs: 'Serena logs',
            },
            desc: {
                serenaProjects: 'Clears the list of projects registered in Serena (settings and comments are kept).',
                serenaLogs: 'Deletes logs produced by Serena.',
            },
        },
    },
    assetManager: {
        title: 'Codex Agent / Skill Management',
        description:
            'List your Codex custom agents and skills, download selected ones together as a ZIP, or upload a ZIP/file to import them.',
        wslSection: 'WSL: {{distro}}',
        tabAgents: 'Agents',
        tabSkills: 'Skills',
        col: {
            name: 'Name',
            description: 'Description',
            model: 'Model',
        },
        columnFiles: 'Files',
        columnLastModified: 'Last modified',
        columnView: 'View',
        newBadge: 'NEW',
        relative: {
            today: 'today',
            yesterday: 'yesterday',
            daysAgo: '{{count}} days ago',
            monthAgo: '1 month ago',
            monthsAgo: '{{count}} months ago',
            yearAgo: '1 year ago',
            yearsAgo: '{{count}} years ago',
        },
        download: 'Download',
        upload: 'Upload',
        delete: 'Delete',
        viewHeader: 'Header',
        viewFull: 'Full',
        viewTitle: 'Header: {{name}}',
        viewFullTitle: 'Full: {{name}}',
        viewFullError: 'Failed to load the content',
        close: 'Close',
        cancel: 'Cancel',
        overwrite: 'Overwrite',
        deleteConfirmTitle: 'Delete the selected items?',
        deleteConfirmBody: 'Delete the {{count}} selected item(s). This cannot be undone. Continue?',
        deleteSuccess: 'Deleted {{count}} item(s)',
        deletePartial: 'Some items could not be deleted because they are in use',
        deleteError: 'Failed to delete the selected items',
        noEntries: 'No data available',
        unavailable: 'This environment cannot access archive operations (the WSL path is unreachable).',
        downloadSuccess: 'Archive saved',
        downloadError: 'Failed to create the archive',
        uploadSuccess: 'Imported {{count}} item(s)',
        uploadError: 'Upload failed',
        overwriteConfirmTitle: 'Overwrite items with the same name?',
        overwriteConfirmBody:
            'The following {{count}} item(s) already exist and will be replaced: {{names}}. Continue?',
        importOfficial: 'Import official skills',
        importOfficialTitle: 'Import official skills',
        importOfficialDesc:
            'Skills from the official OpenAI repository (openai/skills). Select the skills to import. Existing skills with the same name will be replaced.',
        import: 'Import',
        gitRequired: 'This feature requires git to be installed',
        officialImportSuccess: 'Imported {{count}} official skill(s)',
        officialImportError: 'Failed to import official skills',
        officialListError: 'Failed to fetch official skills',
        repoUpdating: 'Updating the official repository...',
        mdNoName: 'Could not read the name from SKILL.md',
        kindWarnTitle: 'The type may not match',
        kindWarnContinue: 'Import anyway',
        kindWarn: {
            'agent-toml-into-skill': 'This file may be an agent (.toml). Import it as a skill?',
            'skill-no-skillmd':
                'This archive does not contain SKILL.md and may not be a valid skill. Import it as a skill?',
            'skillmd-into-agent': 'This file may be a SKILL.md (skill). Import it as an agent?',
        },
        kindBlock: {
            'agent-into-skill':
                'This archive looks like an agent (.toml file). It cannot be imported into the Skills tab. Please use the Agents tab.',
            'skill-into-agent':
                'This archive looks like a skill (a folder containing SKILL.md). It cannot be imported into the Agents tab. Please use the Skills tab.',
            'no-toml': 'This archive does not contain a .toml file and cannot be imported as an agent.',
        },
    },
    settings: {
        title: 'Codex Settings',
        description: 'Edit ~/.codex/config.toml items in a table, or edit the file directly.',
        wslSection: 'WSL: {{distro}}',
        colItem: 'Item',
        colValue: 'Value',
        directEdit: 'Direct edit',
        directEditTitle: 'Edit config.toml directly',
        directEditDesc:
            'Edit the contents of config.toml directly. Saving overwrites the entire file with this content. Make sure it is valid TOML.',
        save: 'Save',
        cancel: 'Cancel',
        unset: 'Unset',
        unsetWithDefault: 'Unset (default: {{default}})',
        enabled: 'Enabled',
        disabled: 'Disabled',
        unknownValue: '{{value}} (saved value; not in current suggestions)',
        directEditValue: 'Edit the file directly',
        saveSuccess: 'Settings saved',
        saveError: 'Failed to save settings',
        readError: 'Failed to read settings',
        invalidToml: 'The TOML syntax is invalid',
        invalidExisting: 'The existing config.toml is broken and cannot be saved. Fix it via direct edit.',
        verifyFailed:
            'Verification of the edit result failed, so saving was aborted. The file is unchanged. Change this item via direct edit.',
        unavailable: 'The settings for this environment cannot be accessed.',
        group: {
            model: 'Model',
            security: 'Security & Behavior',
            display: 'Display',
            data: 'Data',
            features: 'Agents & Features',
        },
        field: {
            model: {
                label: 'Model (model)',
                desc: 'Default model ID. Suggestions follow the current catalog; custom provider model IDs are accepted.',
            },
            modelProvider: {
                label: 'Model provider (model_provider)',
                desc: 'The model provider ID to use (any ID defined under [model_providers]). Default is openai.',
            },
            modelReasoningEffort: {
                label: 'Reasoning effort (model_reasoning_effort)',
                desc: 'Model-dependent reasoning level from none through ultra. Higher levels improve depth but use more time and tokens.',
            },
            modelReasoningSummary: {
                label: 'Reasoning summary (model_reasoning_summary)',
                desc: 'Detail level of the reasoning summary. none disables it.',
            },
            modelVerbosity: {
                label: 'Response verbosity (model_verbosity)',
                desc: 'Response length tendency for GPT-5 models.',
            },
            modelSupportsReasoningSummaries: {
                label: 'Force reasoning summaries (model_supports_reasoning_summaries)',
                desc: 'Force-enable reasoning summaries as if the model supports them.',
            },
            modelContextWindow: {
                label: 'Context window (model_context_window)',
                desc: 'Context window size in tokens. Leave blank for default.',
            },
            approvalPolicy: {
                label: 'Approval policy (approval_policy)',
                desc: 'When to prompt for approval before running commands. It accepts either a simple value (e.g. on-request) or a granular table, so its shape is not fixed and it is changed via direct edit.',
            },
            sandboxMode: {
                label: 'Sandbox (sandbox_mode)',
                desc: 'Strictness of filesystem / network access.',
            },
            webSearch: {
                label: 'Web search (web_search)',
                desc: 'Web search mode (disabled / cached / indexed / live). It accepts either a simple value or a detailed table (context_size / allowed_domains, etc.), so its shape is not fixed and it is changed via direct edit.',
            },
            personality: {
                label: 'Personality (personality)',
                desc: 'Communication style for responses.',
            },
            allowLoginShell: {
                label: 'Allow login shell (allow_login_shell)',
                desc: 'Allow using a login shell when running commands.',
            },
            historyPersistence: {
                label: 'Session history (history.persistence)',
                desc: 'Whether session transcripts are saved. none disables saving.',
            },
            fileOpener: {
                label: 'File opener (file_opener)',
                desc: 'Editor used to open clickable citations. Default is vscode.',
            },
            hideAgentReasoning: {
                label: 'Hide reasoning (hide_agent_reasoning)',
                desc: 'Suppress reasoning events in TUI / exec output.',
            },
            showRawAgentReasoning: {
                label: 'Show raw reasoning (show_raw_agent_reasoning)',
                desc: 'Show raw reasoning content.',
            },
            tuiAnimations: {
                label: 'TUI animations (tui.animations)',
                desc: 'Animation display inside the TUI.',
            },
            tuiShowTooltips: {
                label: 'TUI tooltips (tui.show_tooltips)',
                desc: 'Show onboarding tooltips.',
            },
            projectDocMaxBytes: {
                label: 'AGENTS.md read limit (project_doc_max_bytes)',
                desc: 'Maximum bytes to read from AGENTS.md. Leave blank for default (32 KiB).',
            },
            analyticsEnabled: {
                label: 'Analytics (analytics.enabled)',
                desc: 'Enable metrics collection.',
            },
            feedbackEnabled: {
                label: 'Feedback (feedback.enabled)',
                desc: 'Enable sending feedback.',
            },
            reviewModel: {
                label: 'Review model (review_model)',
                desc: 'Overrides the model used by /review. Unset uses the current session model. Custom model IDs are accepted.',
            },
            planModeReasoningEffort: {
                label: 'Plan reasoning effort (plan_mode_reasoning_effort)',
                desc: 'Overrides reasoning effort only while Codex is in plan mode. Unset follows model_reasoning_effort.',
            },
            modelAutoCompactTokenLimit: {
                label: 'Auto-compact token limit (model_auto_compact_token_limit)',
                desc: 'Overrides the token threshold that triggers conversation compaction. Unset uses model defaults.',
            },
            modelAutoCompactTokenLimitScope: {
                label: 'Auto-compact token scope (model_auto_compact_token_limit_scope)',
                desc: 'Measures the threshold against all tokens (total) or the body after the fixed prefix (body_after_prefix).',
            },
            toolOutputTokenLimit: {
                label: 'Tool output token limit (tool_output_token_limit)',
                desc: 'Maximum tokens retained in context for each tool output.',
            },
            modelCatalogJson: {
                label: 'Model catalog JSON (model_catalog_json)',
                desc: 'Path to a model-catalog override loaded only at startup.',
            },
            openAiBaseUrl: {
                label: 'OpenAI API URL (openai_base_url)',
                desc: 'Overrides the API base URL for the built-in OpenAI provider. This is separate from the ChatGPT login URL.',
            },
            ossProvider: {
                label: 'OSS provider (oss_provider)',
                desc: 'Local-model provider for --oss sessions. Unset prompts at startup; custom provider IDs are accepted.',
            },
            serviceTier: {
                label: 'Service tier (service_tier)',
                desc: 'Preferred service tier. Built-in examples are fast and flex; catalog-defined values are also accepted.',
            },
            approvalsReviewer: {
                label: 'Approval reviewer (approvals_reviewer)',
                desc: 'Chooses whether eligible approval requests go to the user or automatic review.',
            },
            defaultPermissions: {
                label: 'Default permission profile (default_permissions)',
                desc: 'Built-in or [permissions]-defined profile applied when Codex starts.',
            },
            sandboxNetworkAccess: {
                label: 'Workspace network access (sandbox_workspace_write.network_access)',
                desc: 'Allows outbound network access inside the workspace-write sandbox. Default: off.',
            },
            sandboxExcludeTmpdirEnvVar: {
                label: 'Exclude TMPDIR writes (sandbox_workspace_write.exclude_tmpdir_env_var)',
                desc: 'Excludes the directory named by $TMPDIR from workspace-write writable roots.',
            },
            sandboxExcludeSlashTmp: {
                label: 'Exclude /tmp writes (sandbox_workspace_write.exclude_slash_tmp)',
                desc: 'Excludes /tmp from workspace-write writable roots.',
            },
            tuiNotificationMethod: {
                label: 'Terminal notification method (tui.notification_method)',
                desc: 'Selects automatic detection, OSC 9, or the terminal bell for notifications.',
            },
            tuiNotificationCondition: {
                label: 'Terminal notification condition (tui.notification_condition)',
                desc: 'Notifies only when unfocused or always. Default: unfocused.',
            },
            tuiAlternateScreen: {
                label: 'Alternate screen (tui.alternate_screen)',
                desc: 'Selects automatic, always, or never for TUI alternate-screen use. auto preserves Zellij scrollback.',
            },
            tuiTheme: {
                label: 'TUI theme (tui.theme)',
                desc: 'Syntax-highlighting theme saved by /theme. Custom .tmTheme files under $CODEX_HOME/themes are supported.',
            },
            historyMaxBytes: {
                label: 'History size limit (history.max_bytes)',
                desc: 'Maximum history-file size in bytes. Oldest entries are trimmed when exceeded.',
            },
            checkForUpdateOnStartup: {
                label: 'Check updates at startup (check_for_update_on_startup)',
                desc: 'Checks for a newer Codex version at startup. Default: on.',
            },
            disablePasteBurst: {
                label: 'Disable paste-burst detection (disable_paste_burst)',
                desc: 'Disables TUI detection that treats a rapid burst of input as a paste. Default: off.',
            },
            modelInstructionsFile: {
                label: 'Base instructions file (model_instructions_file)',
                desc: 'Path to a file that replaces the built-in Codex base instructions.',
            },
            developerInstructions: {
                label: 'Additional developer instructions (developer_instructions)',
                desc: 'Additional user instructions injected before AGENTS.md.',
            },
            compactPrompt: {
                label: 'Compact prompt (compact_prompt)',
                desc: 'Inline override for the built-in history-compaction prompt.',
            },
            experimentalCompactPromptFile: {
                label: 'Compact prompt file (experimental_compact_prompt_file)',
                desc: 'Path to a file containing an experimental history-compaction prompt override.',
            },
            logDir: {
                label: 'Log directory (log_dir)',
                desc: 'Overrides the Codex log directory. Setting it explicitly also enables codex-tui.log.',
            },
            sqliteHome: {
                label: 'SQLite state directory (sqlite_home)',
                desc: 'Overrides the directory for SQLite-backed runtime state.',
            },
            backgroundTerminalMaxTimeout: {
                label: 'Background terminal wait limit (background_terminal_max_timeout)',
                desc: 'Maximum empty write_stdin wait in milliseconds for background terminals. Default: five minutes.',
            },
            cliAuthCredentialsStore: {
                label: 'Login credential store (cli_auth_credentials_store)',
                desc: 'Stores CLI login credentials in a file, OS keyring, or automatic selection. Default: file.',
            },
            chatgptBaseUrl: {
                label: 'ChatGPT login URL (chatgpt_base_url)',
                desc: 'Base URL for the ChatGPT authentication flow, separate from the OpenAI API endpoint.',
            },
            forcedChatgptWorkspaceId: {
                label: 'Forced ChatGPT workspace (forced_chatgpt_workspace_id)',
                desc: 'Restricts ChatGPT login to the specified workspace ID.',
            },
            forcedLoginMethod: {
                label: 'Forced login method (forced_login_method)',
                desc: 'Forces ChatGPT or API-key login instead of automatic selection.',
            },
            mcpOauthCredentialsStore: {
                label: 'MCP OAuth credential store (mcp_oauth_credentials_store)',
                desc: 'Stores MCP OAuth credentials in a file, OS keyring, or automatic selection. Default: auto.',
            },
            mcpOauthCallbackPort: {
                label: 'MCP OAuth callback port (mcp_oauth_callback_port)',
                desc: 'Fixes the local callback listener port for MCP OAuth to a value from 1 through 65535.',
            },
            mcpOauthCallbackUrl: {
                label: 'MCP OAuth callback URL (mcp_oauth_callback_url)',
                desc: 'Overrides the MCP OAuth redirect URL base for remote development environments and similar setups.',
            },
            windowsWslSetupAcknowledged: {
                label: 'WSL setup acknowledged (windows_wsl_setup_acknowledged)',
                desc: 'Records that Windows WSL onboarding was acknowledged. Normally managed by Codex.',
            },
            suppressUnstableFeaturesWarning: {
                label: 'Hide unstable-feature warning (suppress_unstable_features_warning)',
                desc: 'Suppresses the warning shown when development or experimental feature flags are enabled.',
            },
            shellEnvironmentInherit: {
                label: 'Shell environment inheritance (shell_environment_policy.inherit)',
                desc: 'Inherits all variables, core variables only, or none in child processes.',
            },
            shellEnvironmentIgnoreDefaultExcludes: {
                label: 'Ignore secret-name exclusions (shell_environment_policy.ignore_default_excludes)',
                desc: 'Disables default exclusion of names containing KEY, SECRET, or TOKEN. Use carefully to avoid exposing secrets.',
            },
            shellEnvironmentExperimentalUseProfile: {
                label: 'Use shell profile (shell_environment_policy.experimental_use_profile)',
                desc: 'Builds child-process environments through the user shell profile. Experimental.',
            },
            agentsMaxThreads: {
                label: 'Concurrent agents (agents.max_threads)',
                desc: 'Maximum concurrently open agent threads. Default: 6.',
            },
            agentsMaxDepth: {
                label: 'Agent nesting depth (agents.max_depth)',
                desc: 'Maximum depth at which subagents can spawn children. The root is depth 0; default is 1.',
            },
            agentsJobMaxRuntimeSeconds: {
                label: 'Agent job runtime (agents.job_max_runtime_seconds)',
                desc: 'Default maximum runtime per spawn_agents_on_csv worker. Unset falls back to 1800 seconds.',
            },
            agentsInterruptMessage: {
                label: 'Record interrupt message (agents.interrupt_message)',
                desc: 'Adds a model-visible history message when an agent turn is interrupted. Default: on.',
            },
            featuresGoals: {
                label: 'Goals (features.goals)',
                desc: 'Enables goal-based outcome and progress tracking for long tasks. Stable and on by default.',
            },
            featuresHooks: {
                label: 'Lifecycle hooks (features.hooks)',
                desc: 'Loads configured lifecycle hooks around events such as tool execution. On by default.',
            },
            featuresFastMode: {
                label: 'Fast mode (features.fast_mode)',
                desc: 'Makes fast mode available for supported models. Stable and on by default.',
            },
            featuresMemories: {
                label: 'Local memories (features.memories)',
                desc: 'Enables experimental generation and use of local memories from prior tasks. Off by default.',
            },
            memoriesGenerate: {
                label: 'Generate memories (memories.generate_memories)',
                desc: 'Generates local memories from eligible new tasks for future use. Requires features.memories.',
            },
            memoriesUse: {
                label: 'Use memories (memories.use_memories)',
                desc: 'Injects existing local memories into future session context. Requires features.memories.',
            },
            memoriesDisableOnExternalContext: {
                label: 'Skip external-context memories (memories.disable_on_external_context)',
                desc: 'Excludes tasks that used external context such as MCP, web search, or tool search from memory generation.',
            },
            memoriesMinRateLimitRemainingPercent: {
                label: 'Memory rate-limit threshold (memories.min_rate_limit_remaining_percent)',
                desc: 'Minimum remaining Codex rate-limit percentage, from 0 through 100, required before memory generation starts.',
            },
            memoriesExtractModel: {
                label: 'Memory extraction model (memories.extract_model)',
                desc: 'Overrides the model used to extract memory candidates from each task.',
            },
            memoriesConsolidationModel: {
                label: 'Memory consolidation model (memories.consolidation_model)',
                desc: 'Overrides the model used to organize and consolidate local memories.',
            },
            featuresMultiAgent: {
                label: 'Multi-agent (features.multi_agent)',
                desc: 'Enables spawning, steering, and waiting on subagents. On by default.',
            },
            featuresPersonality: {
                label: 'Personality feature (features.personality)',
                desc: 'Enables the personality setting and in-session response-style controls. On by default.',
            },
            featuresRemotePlugin: {
                label: 'Remote plugins (features.remote_plugin)',
                desc: 'Enables retrieval and use of remotely distributed Codex plugins. On by default.',
            },
            featuresShellSnapshot: {
                label: 'Shell environment snapshot (features.shell_snapshot)',
                desc: 'Captures the startup shell environment for reuse by later commands. On by default.',
            },
            featuresShellTool: {
                label: 'Shell tool (features.shell_tool)',
                desc: 'Enables the shell command-execution tool. Stable and on by default.',
            },
            featuresUnifiedExec: {
                label: 'Unified execution sessions (features.unified_exec)',
                desc: 'Enables the unified command and follow-up stdin execution backend. Stable and off by default.',
            },
            featuresApps: {
                label: 'App connectors (features.apps)',
                desc: 'Allows Codex to use connected apps and connectors. Stable and on by default.',
            },
            featuresNetworkProxy: {
                label: 'Sandbox network proxy (features.network_proxy)',
                desc: 'Permission-profile-controlled sandbox networking. It accepts either a simple on/off value or a detailed table (proxy_url, etc.), so its shape is not fixed and it is changed via direct edit.',
            },
            featuresEnableRequestCompression: {
                label: 'Request compression (features.enable_request_compression)',
                desc: 'Compresses transport data for supported model requests. Stable and on by default.',
            },
            featuresSkillMcpDependencyInstall: {
                label: 'Install skill MCP dependencies (features.skill_mcp_dependency_install)',
                desc: 'Enables the installation flow for MCP dependencies required by skills. Stable and on by default.',
            },
            featuresPreventIdleSleep: {
                label: 'Prevent sleep while running (features.prevent_idle_sleep)',
                desc: 'Prevents system idle sleep while Codex is working. Experimental and off by default.',
            },
            modelProviders: {
                label: 'Model provider definitions (model_providers.<id>)',
                desc: 'Defines endpoints, authentication, headers, and retry settings for custom model providers.',
            },
            sandboxWritableRoots: {
                label: 'Additional writable roots (sandbox_workspace_write.writable_roots)',
                desc: 'Paths writable outside the workspace when the workspace-write sandbox is active.',
            },
            permissionsProfiles: {
                label: 'Permission profiles (permissions.<name>)',
                desc: 'Defines filesystem, workspace-root, and network rules for named permission profiles.',
            },
            notify: {
                label: 'External notifier command (notify)',
                desc: 'Program and argument array invoked for turn-completion notifications. Disabled when unset.',
            },
            tuiNotifications: {
                label: 'TUI notification events (tui.notifications)',
                desc: 'Enables or disables desktop notifications, or limits them to selected event IDs. On by default.',
            },
            tuiStatusLine: {
                label: 'TUI status line (tui.status_line)',
                desc: 'Orders footer item IDs such as model, remaining context, and Git branch.',
            },
            tuiTerminalTitle: {
                label: 'Terminal title (tui.terminal_title)',
                desc: 'Orders the item IDs shown in the terminal window or tab title.',
            },
            tuiKeymap: {
                label: 'TUI key bindings (tui.keymap)',
                desc: 'Overrides TUI action bindings for contexts such as global, composer, and chat.',
            },
            projectDocFallbackFilenames: {
                label: 'Instruction fallback filenames (project_doc_fallback_filenames)',
                desc: 'Ordered fallback filenames checked when AGENTS.md is absent at a directory level.',
            },
            projectRootMarkers: {
                label: 'Project root markers (project_root_markers)',
                desc: 'Filenames used while searching parent directories to determine the project root.',
            },
            shellEnvironmentExclude: {
                label: 'Environment exclusion patterns (shell_environment_policy.exclude)',
                desc: 'Case-insensitive glob patterns removed from the environment inherited by child processes.',
            },
            shellEnvironmentSet: {
                label: 'Environment overrides (shell_environment_policy.set)',
                desc: 'Key-value map that explicitly adds or overrides environment variables for child processes.',
            },
            shellEnvironmentIncludeOnly: {
                label: 'Environment allowlist (shell_environment_policy.include_only)',
                desc: 'When non-empty, limits inherited environment variables to matching names.',
            },
            projects: {
                label: 'Project trust settings (projects)',
                desc: 'Records trusted or untrusted worktree state by absolute path.',
            },
            agentsDefinitions: {
                label: 'Agent definitions (agents.<name>)',
                desc: 'Defines named subagents, including descriptions, config files, and nickname candidates.',
            },
            skillsConfig: {
                label: 'Per-skill configuration (skills.config)',
                desc: 'Array of tables that enables or disables a skill by its SKILL.md path.',
            },
            hooks: {
                label: 'Lifecycle hooks (hooks)',
                desc: 'Defines inline command hooks for events such as before and after tool use.',
            },
            mcpServers: {
                label: 'MCP server definitions (mcp_servers.<id>)',
                desc: 'Defines stdio or HTTP connections, authentication, timeouts, and tool controls for MCP servers.',
            },
            apps: {
                label: 'Per-app configuration (apps.<id>)',
                desc: 'Controls app enablement, destructive operations, approvals, and individual tools.',
            },
            toolSuggest: {
                label: 'Tool suggestions (tool_suggest)',
                desc: 'Defines which connectors or plugins Codex may suggest for installation and which are disabled.',
            },
            autoReviewPolicy: {
                label: 'Auto-review policy (auto_review.policy)',
                desc: 'Markdown text that guides automatic-review behavior, describing review criteria and rules.',
            },
            windowsSandbox: {
                label: 'Windows sandbox privilege (windows.sandbox)',
                desc: 'Runs the Windows sandbox unelevated or elevated.',
            },
            windowsSandboxPrivateDesktop: {
                label: 'Windows private desktop (windows.sandbox_private_desktop)',
                desc: 'Runs the Windows sandbox on an isolated private desktop.',
            },
            tuiRawOutputMode: {
                label: 'TUI raw output mode (tui.raw_output_mode)',
                desc: 'Shows command output verbatim without formatting. Default: off.',
            },
            tuiVimModeDefault: {
                label: 'TUI Vim mode default (tui.vim_mode_default)',
                desc: 'Enables Vim key bindings in the input field by default. Default: off.',
            },
            noticeHideFullAccessWarning: {
                label: 'Hide full-access warning (notice.hide_full_access_warning)',
                desc: 'Suppresses the warning shown when danger-full-access is used.',
            },
            noticeHideRateLimitModelNudge: {
                label: 'Hide rate-limit nudge (notice.hide_rate_limit_model_nudge)',
                desc: 'Suppresses the prompt suggesting a different model when a rate limit is reached.',
            },
            noticeHideWorldWritableWarning: {
                label: 'Hide world-writable warning (notice.hide_world_writable_warning)',
                desc: 'Suppresses the warning shown when the workspace is world-writable.',
            },
            otelEnvironment: {
                label: 'OpenTelemetry environment (otel.environment)',
                desc: 'Environment name (deployment.environment) attached to telemetry. Default: dev.',
            },
            otelMetricsExporter: {
                label: 'Metrics exporter (otel.metrics_exporter)',
                desc: 'Selects the metrics destination: none, statsig, OTLP/HTTP, or OTLP/gRPC. Default: statsig.',
            },
            otelTraceExporter: {
                label: 'Trace exporter (otel.trace_exporter)',
                desc: 'Selects the trace destination: none, OTLP/HTTP, or OTLP/gRPC.',
            },
            otelExporter: {
                label: 'Log exporter (otel.exporter)',
                desc: 'Selects the log-event destination: none, OTLP/HTTP, or OTLP/gRPC.',
            },
            otelLogUserPrompt: {
                label: 'Export raw prompts (otel.log_user_prompt)',
                desc: 'Includes raw user prompt text in telemetry. Use carefully to avoid exposing sensitive data.',
            },
            toolsViewImage: {
                label: 'Image attach tool (tools.view_image)',
                desc: 'Enables the view_image tool that attaches local image files to context.',
            },
            memoriesMaxRawMemoriesForConsolidation: {
                label: 'Consolidation input limit (memories.max_raw_memories_for_consolidation)',
                desc: 'Maximum raw memories handled in one consolidation pass. Default: 256, max: 4096.',
            },
            memoriesMaxRolloutAgeDays: {
                label: 'Max rollout age for extraction (memories.max_rollout_age_days)',
                desc: 'Maximum age in days of rollouts eligible for memory extraction. Default: 30, range 0-90.',
            },
            memoriesMaxRolloutsPerStartup: {
                label: 'Rollouts per startup (memories.max_rollouts_per_startup)',
                desc: 'Maximum rollouts sent to memory extraction per startup. Default: 16, max: 128.',
            },
            memoriesMaxUnusedDays: {
                label: 'Max unused days (memories.max_unused_days)',
                desc: 'Maximum days an unused memory is retained. Default: 30, range 0-365.',
            },
            memoriesMinRolloutIdleHours: {
                label: 'Extraction idle time (memories.min_rollout_idle_hours)',
                desc: 'Minimum idle hours before a rollout becomes eligible for memory extraction. Default: 6, range 1-48.',
            },
            featuresCodeModeEnabled: {
                label: 'Code mode (features.code_mode.enabled)',
                desc: 'Enables code mode, which invokes MCP tools through code. Off by default.',
            },
            featuresRolloutBudgetEnabled: {
                label: 'Rollout budget (features.rollout_budget.enabled)',
                desc: 'Enables the rollout-budget feature that manages a session token budget. Off by default.',
            },
            featuresRolloutBudgetLimitTokens: {
                label: 'Rollout budget limit (features.rollout_budget.limit_tokens)',
                desc: 'Maximum total tokens allowed as the rollout budget.',
            },
            featuresRolloutBudgetPrefillTokenWeight: {
                label: 'Prefill token weight (features.rollout_budget.prefill_token_weight)',
                desc: 'Weight applied to prefill (input) tokens in budget accounting. Default: 1.',
            },
            featuresRolloutBudgetSamplingTokenWeight: {
                label: 'Sampling token weight (features.rollout_budget.sampling_token_weight)',
                desc: 'Weight applied to sampling (output) tokens in budget accounting. Default: 1.',
            },
            featuresRolloutBudgetReminderIntervalTokens: {
                label: 'Budget reminder interval (features.rollout_budget.reminder_interval_tokens)',
                desc: 'Token-consumption interval at which the remaining budget is reported.',
            },
            appsDefaultEnabled: {
                label: 'Default app enablement (apps._default.enabled)',
                desc: 'Default enabled state applied to apps without individual configuration. On by default.',
            },
            appsDefaultDefaultToolsEnabled: {
                label: 'Default app tools (apps._default.default_tools_enabled)',
                desc: 'Whether default tools are enabled by default for apps without individual configuration.',
            },
            appsDefaultDestructiveEnabled: {
                label: 'Default app destructive ops (apps._default.destructive_enabled)',
                desc: 'Whether destructive operations are allowed by default for apps without individual configuration.',
            },
            appsDefaultOpenWorldEnabled: {
                label: 'Default app open-world access (apps._default.open_world_enabled)',
                desc: 'Whether open-world access is allowed by default for apps without individual configuration.',
            },
        },
    },
    pluginManager: {
        title: 'Codex Plugin Manager',
        description:
            'List, install, and uninstall Codex plugins and manage marketplaces. Operations use the codex command.',
    },
    nav: {
        codexMcp: 'Codex MCP Management',
        codexAgentSkill: 'Codex Agent / Skill Management',
        pluginManager: 'Codex Plugin Manager',
        codexCleanup: 'Codex Cleanup',
        codexSettings: 'Codex Settings',
    },
    dashboard: {
        codexMcpDesc: 'Enable/disable/reorder MCP servers for Codex (CLI).',
        codexAgentSkillDesc: 'Manage Codex agents and skills.',
        pluginManagerDesc: 'Manage Codex plugins and marketplaces.',
        codexCleanupDesc: 'Clean up directories under ~/.codex to reclaim space.',
        codexSettingsDesc: 'Edit configuration items in ~/.codex/config.toml.',
    },
};
